export const RISKY_QUESTS = [
  // Social Dares
  "Talk to a complete stranger for 5 minutes",
  "Compliment 5 different strangers today",
  "Ask someone you barely know to hang out",
  "Start a conversation with the person next to you in line",
  "Wave at a stranger and see if they wave back",
  "Ask a stranger for their opinion on something random",
  "Say hi to every person you pass for the next hour",
  "Strike up a conversation with someone at a coffee shop",
  "Ask a stranger what their favorite book is",
  "Introduce yourself to your neighbor if you haven't already",
  "Ask someone you admire for advice",
  "Tell someone you appreciate them out of nowhere",
  "Ask a stranger to take a photo of you somewhere random",
  "Start a conversation with someone waiting for the bus",
  "Ask the cashier how their day is going and actually listen",
  "Compliment a stranger's outfit",
  "Ask someone their life story in under 5 minutes",
  "Tell a joke to a stranger",
  "Ask a stranger for a restaurant recommendation",
  "Smile at every person you see for an entire hour",

  // Embarrassing Public Acts
  "Sing out loud in a public place",
  "Dance in public with no music",
  "Skip instead of walk for the next 10 minutes",
  "Wear something ridiculous for the rest of the day",
  "Do 10 jumping jacks in a public space",
  "Narrate your actions out loud for 5 minutes in public",
  "Walk backwards for an entire block",
  "Pretend to be a tour guide somewhere random",
  "Do your best impression of an animal in public",
  "Speak in an accent for the next hour",
  "Walk around with a sign that says something funny",
  "Do a cartwheel in a park",
  "Sit on the floor somewhere in public and meditate for 2 minutes",
  "Stand on one leg for 1 minute in a crowded place",
  "Bow dramatically after completing any task today",
  "Talk in slow motion for 5 minutes",
  "Walk into a store and ask for something they obviously don't sell",
  "Do the worm in a grassy area",
  "Read a book out loud on public transport",
  "Stand in a busy area and clap slowly for no reason",

  // Physical Challenges
  "Take a cold shower for 2 minutes",
  "Do 50 push-ups right now",
  "Hold a plank for 2 minutes",
  "Run a mile without stopping",
  "Do 100 squats today",
  "Walk barefoot outside for 10 minutes",
  "Hold an ice cube in your hand until it melts",
  "Do 20 pull-ups",
  "Run up and down stairs 10 times",
  "Do a 5 minute wall sit",
  "Hold your breath for as long as you can 3 times",
  "Do 30 burpees without stopping",
  "Walk 10,000 steps today",
  "Take a cold shower for 5 minutes",
  "Do a handstand against the wall for 30 seconds",
  "Jump rope for 5 minutes straight",
  "Do 200 jumping jacks",
  "Run a 5k today",
  "Hold a cold shower for 1 minute then end with cold water",
  "Do a 10 minute intense workout with no breaks",
  "Swim in cold water for 5 minutes",
  "Do 50 sit-ups right now",
  "Hold a deep squat for 2 minutes",
  "Walk on your hands for as long as possible",
  "Do 15 chin-ups",

  // Food Challenges
  "Eat something you've never tried before",
  "Try the spiciest thing on the menu",
  "Eat a spoonful of hot sauce",
  "Try a food combination that sounds disgusting",
  "Eat a whole lemon without making a face",
  "Drink a glass of water as fast as you can",
  "Eat something with your non-dominant hand only",
  "Try food from a cuisine you've never had",
  "Eat a meal completely silently",
  "Try a fruit you've never heard of",
  "Make a meal using only 3 random ingredients",
  "Eat something fermented you've never tried",
  "Put hot sauce on something you normally eat plain",
  "Try the weirdest flavored chips you can find",
  "Eat a raw piece of ginger",
  "Make the spiciest meal you can handle",
  "Try eating with chopsticks for an entire meal",
  "Eat something you hated as a kid and try to enjoy it",
  "Order something random from a menu without looking",
  "Try a bizarre food combination recommended by someone online",
  "Eat a tablespoon of apple cider vinegar",
  "Try durian if you can find it",
  "Eat an entire meal without using your hands",
  "Try the hottest hot sauce available",
  "Make and eat something you've never cooked before",

  // Digital Dares
  "Text your crush right now",
  "Post an embarrassing throwback photo",
  "Send a voice message to someone you haven't talked to in years",
  "Post something genuinely vulnerable on social media",
  "Text someone you've been meaning to reach out to",
  "Post a video of yourself doing something silly",
  "DM someone you admire online",
  "Post your honest opinion about something controversial",
  "Text someone you haven't spoken to in 6 months",
  "Share something you made even if it's not perfect",
  "Post a photo with no filter and no editing",
  "Send a meme to someone you don't know well",
  "Reply to a story you've been ignoring",
  "Post a video of yourself attempting a new skill",
  "Text your parents something heartfelt",
  "Share an unpopular opinion publicly",
  "Post a video of you doing something you're bad at",
  "DM a creator whose work you admire",
  "Text someone who wronged you to forgive them",
  "Post a genuine review of something you use every day",
  "Send a long heartfelt message to an old friend",
  "Post a selfie with an embarrassing caption",
  "Text someone you've been avoiding",
  "Share a creative project you've been hiding",
  "Post a video of you attempting to sing",

  // Facing Fears
  "Watch a horror movie alone in the dark",
  "Go to a place that scares you",
  "Talk to someone you're intimidated by",
  "Sign up for something that terrifies you",
  "Do something you've been avoiding for months",
  "Confront someone about something that's been bothering you",
  "Apply for something you think you're not good enough for",
  "Tell someone a secret you've been keeping",
  "Admit you were wrong to someone",
  "Ask for help with something you're struggling with",
  "Go to a social event alone",
  "Stand at the edge of a high place (safely)",
  "Do something that requires you to be seen",
  "Start the project you've been putting off",
  "Make the call you've been dreading",
  "Go somewhere unfamiliar alone",
  "Try something you failed at before",
  "Express your true feelings to someone",
  "Do something in public that makes you feel vulnerable",
  "Sign up for a class in something you're bad at",
  "Introduce yourself to a group of strangers",
  "Go to a restaurant and eat alone without your phone",
  "Take a different route home and get a little lost",
  "Admit something you're ashamed of to someone you trust",
  "Do karaoke sober",

  // Mental Challenges
  "Meditate for 20 minutes without checking your phone",
  "Go 24 hours without social media",
  "Write down 10 things you're grateful for right now",
  "Spend an entire day without complaining",
  "Go a full day without your phone",
  "Write a letter to your future self",
  "Spend 2 hours completely alone with your thoughts",
  "Journal for 30 minutes straight without stopping",
  "Go 12 hours without eating any sugar",
  "Read for 2 hours straight",
  "Write down your biggest fear and why it scares you",
  "Spend a day doing only things that matter to you",
  "List 20 things you want to accomplish before you die",
  "Go a week without alcohol",
  "Wake up at 5am tomorrow",
  "Go to bed before 10pm tonight",
  "Spend an hour thinking about your life goals",
  "Write down everything you've been procrastinating",
  "Do a full digital detox for 24 hours",
  "Spend 30 minutes visualizing your ideal life",
  "Write an honest letter to someone you hurt",
  "Identify your biggest bad habit and avoid it for 24 hours",
  "Spend a day saying yes to everything reasonable",
  "Learn something completely new for 1 hour",
  "Write your own eulogy",

  // Creative Challenges
  "Write a poem in the next 10 minutes",
  "Draw something without lifting your pen",
  "Make a short video about your day",
  "Write the first chapter of a story",
  "Make something with only materials you have nearby",
  "Sing a song you wrote yourself",
  "Choreograph a 30 second dance",
  "Paint something using only 3 colors",
  "Write a joke and tell it to someone",
  "Make a sculpture out of food",
  "Write a song about your life in 10 minutes",
  "Draw a portrait of someone from memory",
  "Make a short film on your phone",
  "Write a children's story in 20 minutes",
  "Create something using only trash you find",
  "Design your dream house in detail",
  "Write a letter pretending to be your pet",
  "Make up a new game and play it",
  "Create a recipe for a dish that doesn't exist",
  "Write a speech for an imaginary award",
  "Draw a map of your neighborhood from memory",
  "Write a comedy sketch in 15 minutes",
  "Make a playlist for a specific emotion",
  "Create an alter ego and write their backstory",
  "Write a 6 word story about your life",

  // Adventure Dares
  "Go somewhere you've never been in your city",
  "Take a spontaneous day trip",
  "Try a new sport or physical activity today",
  "Go hiking somewhere you've never been",
  "Explore a part of your city you've always ignored",
  "Take public transport somewhere random and explore",
  "Visit a museum or gallery alone",
  "Try an escape room",
  "Go to a comedy show alone",
  "Attend an event for something you know nothing about",
  "Sign up for a race",
  "Book a solo trip somewhere",
  "Go stargazing somewhere dark",
  "Spend a night camping",
  "Try rock climbing",
  "Go to a farmer's market and buy something unusual",
  "Attend a class for something you've never tried",
  "Explore somewhere on a bicycle",
  "Go to a beach or lake and swim",
  "Visit a part of your city at an unusual hour",
  "Find a rooftop with a view",
  "Go to a concert for a band you don't know",
  "Try an extreme sport within your ability",
  "Spend a day as a tourist in your own city",
  "Go on a nature walk with no destination",

  // Relationship Dares
  "Tell someone you love them if you haven't recently",
  "Apologize to someone you've wronged",
  "Reach out to an estranged family member",
  "Plan a surprise for someone you care about",
  "Tell your best friend what you love about them",
  "Write a heartfelt letter to a parent",
  "Reconnect with a friend you've drifted from",
  "Do something kind for a stranger anonymously",
  "Volunteer your time for someone who needs help",
  "Forgive someone who hurt you",
  "Tell someone about a way they inspired you",
  "Plan a date that involves trying something new",
  "Cook a meal for someone you care about",
  "Put your phone away completely during your next conversation",
  "Ask someone deep questions and actually listen",
  "Tell someone a truth you've been hiding",
  "Spend quality time with a family member today",
  "Write thank you notes to 3 people",
  "Do a random act of kindness for a stranger",
  "Have a meaningful conversation with someone you usually small-talk with",

  // Work/Productivity Dares
  "Start the hardest task on your to-do list right now",
  "Work for 4 hours straight with no distractions",
  "Learn a new skill for 2 hours",
  "Send that email you've been drafting for weeks",
  "Ask for a raise or promotion",
  "Pitch your idea to someone",
  "Start the side project you've been dreaming about",
  "Take a real lunch break away from your desk",
  "Declutter your workspace completely",
  "Set a goal and make a concrete plan to achieve it",
  "Do the thing on your list you've been avoiding the longest",
  "Work without music or podcasts for 2 hours",
  "Read a book related to your field",
  "Reach out to a mentor or someone you want to learn from",
  "Organize everything you've been meaning to organize",
  "Do a complete review of your goals",
  "Turn off all notifications for 4 hours and work",
  "Finish something you started and never completed",
  "Ask for feedback on your work from someone honest",
  "Start waking up 1 hour earlier for a week",

  // Silly/Weird Dares
  "Wear your clothes inside out for an hour",
  "Talk in rhymes for 10 minutes",
  "Use a ridiculous nickname for yourself all day",
  "Pretend to be a robot for 5 minutes",
  "Walk around quoting movie lines to yourself",
  "Narrate your life like a nature documentary for 10 minutes",
  "Try to make someone laugh without saying anything",
  "Spend 5 minutes talking to a houseplant",
  "Write a strongly worded letter to an inanimate object",
  "Have a serious debate about something completely absurd",
  "Make up a fake language and use it for 5 minutes",
  "Pretend you're being filmed for a documentary all day",
  "Give everything in your room a dramatic name",
  "Write a formal complaint about the weather",
  "Hold a meeting with your pets",
  "Create an elaborate backstory for a random object",
  "Narrate what you think strangers are thinking",
  "Spend 5 minutes doing your best impressions",
  "Make up a theme song for your day",
  "Pretend every door you open is an important portal",

  // Health and Wellness
  "Drink 3 liters of water today",
  "Go to bed an hour earlier than usual",
  "Do yoga for 30 minutes",
  "Eat only whole foods for the entire day",
  "Take a 30 minute walk with no phone",
  "Do a full body stretch routine",
  "Try intermittent fasting today",
  "Go a full day without caffeine",
  "Do a 20 minute meditation",
  "Cut out all processed food for 24 hours",
  "Do a breathing exercise for 10 minutes",
  "Take a nap without feeling guilty",
  "Spend 30 minutes in nature",
  "Do a digital detox for the evening",
  "Go to sleep before midnight and wake up before 7am",
  "Exercise for 45 minutes",
  "Try a new healthy recipe",
  "Practice gratitude journaling for a week starting now",
  "Go outside first thing in the morning",
  "Cut out sugar for 48 hours",

  // Learning Dares
  "Learn 10 words in a new language today",
  "Watch a documentary about something you know nothing about",
  "Read about a topic you normally avoid",
  "Learn to do something with your non-dominant hand",
  "Take an online course in something new",
  "Learn a magic trick",
  "Study something for 2 hours with full focus",
  "Read a book outside your comfort zone",
  "Learn a new recipe from scratch",
  "Watch a lecture on something completely unfamiliar",
  "Learn the basics of a musical instrument",
  "Teach yourself a basic skill from YouTube",
  "Read something written 100+ years ago",
  "Learn to identify 10 plants or stars",
  "Study a historical event you know nothing about",
  "Learn origami and make something",
  "Figure out how to do something you've always paid someone else to do",
  "Learn 5 interesting facts about a country you know nothing about",
  "Take a class in something that intimidates you",
  "Learn to draw something you couldn't before",

  // Extra Spicy Dares
  "Tell your boss one honest thing you've been holding back",
  "Post something you're proud of that you've been too scared to share",
  "Message your ex to genuinely wish them well",
  "Ask someone on a date",
  "Quit something that's been draining you",
  "Start something you've been too scared to start",
  "Say no to something you would normally say yes to out of fear",
  "Tell someone the truth they need to hear",
  "Do the thing that scares you the most on this list",
  "Make a decision you've been putting off for months",
  "Cut off something or someone that's been holding you back",
  "Share your biggest dream with someone out loud",
  "Admit something you've never admitted to anyone",
  "Ask for what you really want",
  "Take a risk you've been too scared to take",
  "Do something today that your future self will thank you for",
  "Make one big change you've been avoiding",
  "Tell the truth in a situation where lying would be easier",
  "Do the most uncomfortable thing on your to-do list first",
  "Commit to one thing that terrifies you and schedule it",

  // More Social Dares
  "Go to a karaoke bar and actually sing",
  "Ask someone twice your age for life advice",
  "Stand up and speak your mind at a public meeting",
  "Tell someone you barely know something real about yourself",
  "Ask your coworker or classmate about their biggest dream",
  "Compliment someone on something non-physical",
  "Disagree with someone politely in a group setting",
  "Ask someone older than you what they wish they knew at your age",
  "Ask someone you respect to mentor you",
  "Go to a networking event alone",
  "Be the first to break an awkward silence",
  "Ask a group of friends a question you've been afraid to ask",
  "Start a conversation about something meaningful instead of the weather",
  "Approach a group of people you don't know and introduce yourself",
  "Tell someone how they've impacted your life",
  "Introduce two people you know who should meet",
  "Tell a stranger they made your day",
  "Ask someone their opinion and genuinely consider it",
  "Sit next to a stranger on purpose instead of alone",
  "Give a genuine toast at the next social gathering you attend",

  // More Physical Challenges
  "Do a 15 minute HIIT workout right now",
  "Wake up and exercise before doing anything else tomorrow",
  "Do a 1 hour walk without stopping",
  "Try a sport you've never played",
  "Go for a run in the rain",
  "Do 3 sets of the hardest exercise you know",
  "Go to the gym for the first time or return after a long break",
  "Try martial arts for a session",
  "Do a 30 day fitness challenge starting today",
  "Cycle somewhere instead of driving",
  "Try a dance class",
  "Do a sunrise workout",
  "Complete a workout you've never finished before",
  "Exercise until you genuinely can't do another rep",
  "Do 100 push-ups throughout the day",
  "Try a yoga class even though it makes you uncomfortable",
  "Swim 20 laps without stopping",
  "Run somewhere instead of walking",
  "Do a fitness challenge you've seen online",
  "Hold a cold shower for 3 minutes",

  // More Food Challenges
  "Go vegetarian for 24 hours",
  "Make a dish from a country you've never visited",
  "Eat only homemade food for 3 days",
  "Cook a 3 course meal from scratch",
  "Go vegan for 48 hours",
  "Make sushi at home",
  "Cook a meal inspired by your heritage",
  "Try something from a cuisine you've always avoided",
  "Make your own bread from scratch",
  "Eat at a restaurant where you can't read the menu",
  "Make a meal for 10 people",
  "Make homemade pasta from scratch",
  "Go a week eating no takeout",
  "Try every condiment in your fridge on something",
  "Cook using only pantry ingredients for a day",
  "Try a food challenge at a local restaurant",
  "Make a dish with an ingredient you've never cooked with",
  "Try fermented foods for a week",
  "Cook a zero waste meal",
  "Try a food from every continent in one week",

  // More Digital Dares
  "Delete an app you waste time on for a week",
  "Post something creative you made",
  "Share a lesson you learned the hard way",
  "Go 48 hours with no Instagram or TikTok",
  "Text 5 people you care about and tell them you're thinking of them",
  "Post your work in progress even though it's not done",
  "Unfollow everyone who makes you feel bad about yourself",
  "Go through your contacts and reach out to 3 people you miss",
  "Post a genuine behind-the-scenes of something you're working on",
  "Share your honest review of something you use daily",
  "Reply to every message you've been ignoring today",
  "DM someone in your field whose work you respect",
  "Delete 100 photos you don't need",
  "Turn off all notifications for 24 hours",
  "Leave a thoughtful comment on something instead of just liking it",
  "Write and publish something — anything",
  "Curate your feed to only show things that inspire you",
  "Post a video explaining something you're passionate about",
  "Share a book or resource that changed your life",
  "Post something that represents who you really are",

  // More Relationship Dares
  "Plan a surprise for your best friend for no reason",
  "Cook breakfast for someone you live with",
  "Write a list of everything you love about someone and give it to them",
  "Have a completely phone-free dinner with family or friends",
  "Do something your partner or friend has been wanting to do",
  "Ask a parent about their biggest regret and really listen",
  "Tell a sibling or close friend about a time they made you proud",
  "Apologize to someone for something small you dismissed",
  "Make a photo album or memory book for someone",
  "Do a random act of service for a neighbor",
  "Send flowers or a gift to someone for no occasion",
  "Spend an hour listening to someone older tell their story",
  "Forgive yourself for something",
  "Help a friend with something they've been struggling with",
  "Show up for someone who needs it without being asked",
  "Make a playlist for someone and explain why each song reminds you of them",
  "Call instead of texting someone important today",
  "Plan and execute a date night with zero screens",
  "Spend the whole day with someone and give them your full attention",
  "Plan a group activity and actually organize it",

  // More Weird and Silly
  "Wear a cape for an hour",
  "Give everything you do today a dramatic title",
  "Refer to yourself in third person for 10 minutes",
  "Make up a conspiracy theory about something mundane",
  "Write a glowing review of something terrible",
  "Give a TED talk to an empty room",
  "Have an argument with yourself out loud",
  "Make a documentary about your pet",
  "Write a formal apology to a food you don't like",
  "Challenge someone to a staring contest",
  "Make a to-do list for a fictional character",
  "Write a pitch for a ridiculous business idea",
  "Make up a holiday and explain how it's celebrated",
  "Describe your day using only movie titles",
  "Give a sports commentary on something you're doing",
  "Write your autobiography in 10 sentences",
  "Make a weather forecast for your mood",
  "Write a news article about something that happened at home today",
  "Create a coat of arms for your family",
  "Pretend you're from the past for a conversation",

  // Final Batch
  "Go a full day speaking only when necessary",
  "Do something today that scares you a little",
  "Make eye contact and smile at 10 people today",
  "Do something nice for someone without telling anyone",
  "Spend one hour doing absolutely nothing",
  "Try something you said you'd never do",
  "Stop making excuses and just start",
  "Do the thing you keep saying you'll do tomorrow",
  "Be completely honest for 24 hours",
  "Don't check your phone for the first hour after waking up",
  "Write down your top 3 excuses and challenge each one",
  "Do something your past self would be proud of",
  "Make one decision based on logic not fear",
  "Stop waiting for the perfect moment and act now",
  "Try to surprise yourself today",
  "Do something you've never done on a weekday",
  "Say yes to the next opportunity that scares you",
  "Take the harder path today",
  "Do something that makes a good story",
  "End today better than you started it",
  "Make one decision today that future you will thank you for",
  "Try something embarrassing and don't apologize for it",
  "Do something completely out of character today",
  "Challenge one belief you've held for years",
  "Start something you've always wanted to finish",
  "Refuse to take the safe option today",
  "Do something that requires courage",
  "Try something you've always been too proud to try",
  "Make today memorable for one reason",
  "Do the hardest thing on your list first today",
  "Take one real risk today",
  "Make one bold move",
  "Push past your comfort zone in one specific way",
  "Do something that would make the best version of you proud",
  "Go further than you think you can today",
  "Try something where failure is possible",
  "Do something that requires you to be brave",
  "Make one choice that changes your trajectory",
  "Do one thing that feels impossible and prove yourself wrong",
  "Take action on something instead of just thinking about it",
  "Do something that you'll remember in 10 years",
  "Make one move toward the life you actually want",
  "Do something that requires you to show up fully",
  "Try something that requires real effort",
  "Make today count",
];
